type = "services"
title = "Services"
description = "Professional services and community involvement."

[[roles]]
role = "Area Chair"

[[roles.items]]
conference = "NAACL"
year = 2027
icon = "/services/naacl2027.png"

[[roles.items]]
conference = "EMNLP"
year = 2026
note = "Emergency"
icon = "/services/emnlp2026.png"

[[roles]]
role = "Reviewer"

[[roles.items]]
conference = "EACL"
year = 2027
icon = "/services/eacl2027.png"

[[roles.items]]
conference = "ICLR"
year = 2027

[[roles.items]]
conference = "EMNLP"
year = 2026
icon = "/services/emnlp2026.png"

[[roles.items]]
conference = "ARR"
year = 2026
note = "March"

[[roles.items]]
conference = "TrustNLP@ACL"
year = 2026

[[roles.items]]
conference = "ACL"
year = 2026
icon = "/services/acl2026.png"

[[roles.items]]
conference = "EACL"
year = 2026
icon = "/services/eacl2026.png"

[[roles.items]]
conference = "AACL"
year = 2026
icon = "/services/aacl2026.png"

[[roles.items]]
conference = "EMNLP"
year = 2025
icon = "/services/emnlp2025.png"

[[roles.items]]
conference = "ACL"
year = 2025
icon = "/services/acl2025.png"

[[roles.items]]
conference = "COLING"
year = 2025
icon = "/services/coling2025.png"

[[roles.items]]
conference = "ICLR"
year = 2025

[[roles.items]]
conference = "NAACL"
year = 2025
icon = "/services/naacl2025.png"

[[roles.items]]
conference = "ARR"
year = 2024
note = "December"
